import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case system
    case zhHans
    case en

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .system:
            "System"
        case .zhHans:
            "中文"
        case .en:
            "English"
        }
    }

    var usesChinese: Bool {
        switch self {
        case .zhHans:
            true
        case .en:
            false
        case .system:
            Locale.preferredLanguages.first?.lowercased().hasPrefix("zh") == true
        }
    }
}

enum AppCopy {
    static func text(_ key: String, language: AppLanguage) -> String {
        if language.usesChinese, let value = zhHans[key] {
            return value
        }
        return en[key] ?? key
    }

    private static let en: [String: String] = [
        "app.name": "StupidMirror",
        "dashboard.subtitle": "Select a USB device, then open it as a standalone mirror window.",
        "toolbar.autoStart": "Auto-start",
        "toolbar.stop": "Stop",
        "toolbar.settings": "Settings",
        "toolbar.diagnostics": "Diagnostics",
        "toolbar.refresh": "Refresh",
        "metric.devices": "Devices",
        "metric.mirrorWindows": "Mirror windows",
        "metric.controlReady": "Control ready",
        "permission.title": "Camera Permission Needed",
        "permission.body": "macOS exposes the USB iPhone screen as an AVFoundation capture source. Grant Camera permission to the terminal or packaged app, then relaunch.",
        "permission.body.notDetermined": "macOS exposes the USB iPhone screen as an AVFoundation capture source. Click Request Camera Access first, then allow StupidMirror in the system prompt.",
        "permission.body.denied": "Camera access has already been denied or restricted. Open Camera Settings, enable StupidMirror, then return and recheck permission.",
        "permission.requestAccess": "Request Camera Access",
        "permission.openSettings": "Open Camera Settings",
        "permission.recheck": "Recheck Permission",
        "empty.title": "No iPhone Screen Sources",
        "empty.body": "Connect an iPhone over USB, trust this Mac, unlock once if needed, then refresh.",
        "status.controlPreparing": "Preparing local control service...",
        "status.controlPreparingAgent": "Preparing control agent on this iPhone...",
        "status.controlNoUDID": "Control needs a mapped iPhone UDID. Reconnect the iPhone and trust this Mac.",
        "status.controlAppiumUnavailable": "Control service is not ready. Use the bundled Mac app build, enable iPhone automation permissions, then try Control again.",
        "menu.showDashboard": "Show Dashboard",
        "menu.refreshDevices": "Refresh Devices",
        "menu.devices": "Devices",
        "menu.noDevices": "No iPhone screen sources",
        "menu.openAll": "Open All Devices",
        "menu.stopAll": "Stop All Mirrors",
        "menu.quit": "Quit StupidMirror",
        "menu.open": "Open",
        "menu.live": "Live",
        "menu.reconnecting": "Reconnecting",
        "card.defaultSubtitle": "iOS screen source",
        "card.ready": "Ready to mirror",
        "card.open": "Mirror window is open",
        "card.reconnecting": "Waiting for device",
        "card.thumbnailFresh": "Latest snapshot. Click to open a standalone mirror window.",
        "card.thumbnailLoading": "Capturing a fresh thumbnail...",
        "card.thumbnailUnavailable": "Thumbnail unavailable",
        "card.openMirror": "Open Mirror",
        "card.stopMirror": "Stop Mirror",
        "card.connectControl": "Connect Control",
        "card.installControlAgent": "Install Control Agent",
        "card.refreshThumbnail": "Refresh Thumbnail",
        "card.openButton": "Open",
        "card.closeButton": "Close",
        "card.waitingButton": "Waiting",
        "detail.selectTitle": "Select a Device",
        "detail.selectBody": "Pick an iPhone from the sidebar to see its screen and open a mirror window.",
        "detail.openMirror": "Open Mirror Window",
        "detail.closeMirror": "Close Mirror Window",
        "detail.control": "Control",
        "detail.connectControl": "Connect",
        "detail.installControlAgent": "Install / Connect",
        "detail.disconnectControl": "Disconnect",
        "detail.lastSnapshot": "Live snapshot",
        "settings.subtitle": "Mirror startup and advanced control-agent settings.",
        "settings.language": "Language",
        "settings.mirroring": "Mirroring",
        "settings.autoOpen": "Open mirror windows automatically when new devices appear",
        "settings.control": "Control",
        "settings.appiumURL": "Appium server URL",
        "settings.bundleID": "Bundle ID to launch",
        "settings.xcodeTeam": "Apple Team ID",
        "settings.xcodeSigningID": "Signing identity",
        "settings.wdaBundleID": "WDA bundle ID",
        "settings.usePrebuiltWDA": "Reuse prebuilt WDA",
        "settings.check": "Check",
        "settings.startAppium": "Start Appium",
        "settings.stop": "Stop",
        "settings.appiumHelp": "Mirroring does not need an iOS app. Control is explicit: when you click Install / Connect, StupidMirror starts its bundled Appium runtime and asks XCUITest to install or start WebDriverAgent on the iPhone.",
        "diagnostics.runtime": "Runtime",
        "diagnostics.devices": "Devices",
        "diagnostics.noDevices": "No AVFoundation .muxed iPhone screen source is currently visible.",
        "diagnostics.controlPrereq": "Control prerequisites",
        "diagnostics.controlHelp": "Mirror-only users do not need an iOS app. Control installs or starts WebDriverAgent from the Mac after you click Install / Connect. The iPhone must trust this Mac and allow Developer Mode/UI Automation.",
        "common.close": "Close",
        "common.noUDID": "No UDID mapped",
        "common.notSet": "Not set",
        "common.default": "Default",
        "common.cancel": "Cancel",
        "mirror.pause": "Pause Mirror",
        "mirror.start": "Start Mirror",
        "mirror.disconnectControl": "Disconnect Control",
        "mirror.home": "Home",
        "mirror.appSwitcher": "App Switcher",
        "mirror.back": "Back",
        "mirror.pasteClipboard": "Paste Clipboard",
        "mirror.close": "Close Mirror",
        "mirror.floatOnTop": "Keep on Top",
        "mirror.size": "Window Size",
        "mirror.size.small": "Small",
        "mirror.size.medium": "Medium",
        "mirror.size.large": "Large",
        "mirror.reconnectingBody": "The mirror window was closed. The device will become available here when it reconnects.",
        "status.ready": "Ready",
        "status.deviceConnectedRefreshing": "Device connected. Refreshing...",
        "status.deviceDisconnectedRefreshing": "Device disconnected. Refreshing...",
        "status.permissionRequired": "Camera permission is required because iPhone screen sources are exposed through AVFoundation.",
        "status.noSources": "No iPhone screen sources found. Connect an iPhone by USB, unlock it if needed, trust this Mac, then refresh.",
        "status.foundOne": "Found 1 iPhone screen source.",
        "status.foundMany": "Found %d iPhone screen sources.",
        "status.reconnecting": "Waiting for %d device to reconnect.",
        "status.reconnectingMany": "Waiting for %d devices to reconnect.",
        "diagnostic.camera": "Camera permission",
        "diagnostic.backend": "Mirror backend",
        "diagnostic.detected": "Detected screen sources",
        "diagnostic.reconnecting": "Reconnecting devices",
        "diagnostic.autoStart": "Auto-start mirrors",
        "diagnostic.appiumServer": "Appium server",
        "diagnostic.appiumService": "Appium service",
        "diagnostic.controlBundle": "Control bundle",
        "diagnostic.xcodeTeam": "Apple Team ID",
        "diagnostic.wdaBundle": "WDA bundle",
        "diagnostic.libimobiledevice": "libimobiledevice",
        "diagnostic.mirror": "Mirror",
        "diagnostic.control": "Control",
        "common.on": "On",
        "common.off": "Off",
        "connection.connected": "Connected",
        "connection.disconnected": "Reconnecting",
        "connection.unavailable": "Unavailable",
        "mirror.state.stopped": "Stopped",
        "mirror.state.starting": "Starting",
        "mirror.state.running": "Live",
        "mirror.state.failed": "Failed",
        "control.state.unavailable": "Control not connected",
        "control.state.connecting": "Connecting",
        "control.state.ready": "Control ready",
        "control.state.failed": "Control failed",
        "control.phase.appium": "Starting service",
        "control.phase.wda": "Installing agent",
        "control.phase.screen": "Reading screen",
        "control.error.unlockDevice": "Unlock iPhone and keep it awake, then retry Install / Connect.",
        "control.error.developerMode": "Enable Developer Mode on iPhone, then retry Install / Connect.",
        "control.error.uiAutomation": "Enable UI Automation for this iPhone, then retry Install / Connect.",
        "control.error.trustDevice": "Trust this Mac on iPhone, then reconnect USB and retry.",
        "control.error.signing": "WDA signing failed. Check Apple Team ID and WDA bundle ID in Settings.",
        "control.error.wdaNotReady": "WebDriverAgent did not become ready. Unlock iPhone and retry Install / Connect.",
        "appium.state.unknown": "Unknown",
        "appium.state.checking": "Checking",
        "appium.state.starting": "Starting",
        "appium.state.running": "Running",
        "appium.state.stopped": "Stopped",
        "appium.state.missing": "Missing",
        "appium.state.failed": "Failed",
        "auth.authorized": "Authorized",
        "auth.notDetermined": "Not determined",
        "auth.denied": "Denied",
        "auth.restricted": "Restricted",
        "auth.unknown": "Unknown"
    ]

    private static let zhHans: [String: String] = [
        "app.name": "StupidMirror",
        "dashboard.subtitle": "选择 USB 设备，然后用独立镜像窗口打开。",
        "toolbar.autoStart": "自动打开",
        "toolbar.stop": "停止",
        "toolbar.settings": "设置",
        "toolbar.diagnostics": "诊断",
        "toolbar.refresh": "刷新",
        "metric.devices": "设备",
        "metric.mirrorWindows": "镜像窗口",
        "metric.controlReady": "控制就绪",
        "permission.title": "需要相机权限",
        "permission.body": "macOS 会把 USB iPhone 屏幕暴露成 AVFoundation 采集源。请给终端或打包后的 App 授予相机权限，然后重新打开。",
        "permission.body.notDetermined": "macOS 会把 USB iPhone 屏幕暴露成 AVFoundation 采集源。请先点击请求相机权限，然后在系统弹窗里允许 StupidMirror。",
        "permission.body.denied": "相机权限已经被拒绝或受限。请打开相机权限设置，启用 StupidMirror，然后回到应用里重新检查。",
        "permission.requestAccess": "请求相机权限",
        "permission.openSettings": "打开相机权限设置",
        "permission.recheck": "重新检查权限",
        "empty.title": "没有发现 iPhone 屏幕源",
        "empty.body": "用 USB 连接 iPhone，信任这台 Mac，必要时先解锁一次，然后刷新。",
        "status.controlPreparing": "正在准备本机控制服务...",
        "status.controlPreparingAgent": "正在为这台 iPhone 准备控制代理...",
        "status.controlNoUDID": "控制需要匹配到 iPhone UDID。请重新连接 iPhone，并在手机上信任这台 Mac。",
        "status.controlAppiumUnavailable": "控制服务还没准备好。请使用打包后的 Mac App、打开 iPhone 自动化权限后，再点一次控制。",
        "menu.showDashboard": "显示控制台",
        "menu.refreshDevices": "刷新设备",
        "menu.devices": "设备",
        "menu.noDevices": "没有 iPhone 屏幕源",
        "menu.openAll": "打开全部设备",
        "menu.stopAll": "停止所有镜像",
        "menu.quit": "退出 StupidMirror",
        "menu.open": "打开",
        "menu.live": "镜像中",
        "menu.reconnecting": "重连中",
        "card.defaultSubtitle": "iOS 屏幕源",
        "card.ready": "可以开始镜像",
        "card.open": "镜像窗口已打开",
        "card.reconnecting": "等待设备重连",
        "card.thumbnailFresh": "最新缩略图。点击打开独立镜像窗口。",
        "card.thumbnailLoading": "正在捕获缩略图...",
        "card.thumbnailUnavailable": "缩略图不可用",
        "card.openMirror": "打开镜像",
        "card.stopMirror": "停止镜像",
        "card.connectControl": "连接控制",
        "card.installControlAgent": "安装控制代理",
        "card.refreshThumbnail": "刷新缩略图",
        "card.openButton": "打开",
        "card.closeButton": "关闭",
        "card.waitingButton": "等待中",
        "detail.selectTitle": "选择一台设备",
        "detail.selectBody": "在左侧选择一台 iPhone，查看画面并打开镜像窗口。",
        "detail.openMirror": "打开镜像窗口",
        "detail.closeMirror": "关闭镜像窗口",
        "detail.control": "控制",
        "detail.connectControl": "连接",
        "detail.installControlAgent": "安装/连接",
        "detail.disconnectControl": "断开",
        "detail.lastSnapshot": "实时快照",
        "settings.subtitle": "镜像启动和高级控制代理配置。",
        "settings.language": "语言",
        "settings.mirroring": "镜像",
        "settings.autoOpen": "新设备出现时自动打开镜像窗口",
        "settings.control": "控制",
        "settings.appiumURL": "Appium 服务地址",
        "settings.bundleID": "启动的 Bundle ID",
        "settings.xcodeTeam": "Apple Team ID",
        "settings.xcodeSigningID": "签名身份",
        "settings.wdaBundleID": "WDA Bundle ID",
        "settings.usePrebuiltWDA": "复用已构建的 WDA",
        "settings.check": "检查",
        "settings.startAppium": "启动 Appium",
        "settings.stop": "停止",
        "settings.appiumHelp": "只镜像不需要 iOS App。控制需要用户明确点击安装/连接；StupidMirror 会启动内置 Appium runtime，并让 XCUITest 在 iPhone 上安装或启动 WebDriverAgent。",
        "diagnostics.runtime": "运行时",
        "diagnostics.devices": "设备",
        "diagnostics.noDevices": "当前没有可见的 AVFoundation .muxed iPhone 屏幕源。",
        "diagnostics.controlPrereq": "控制前置条件",
        "diagnostics.controlHelp": "只镜像不需要 iOS App。控制会在点击安装/连接后由 Mac 安装或启动 WebDriverAgent。iPhone 仍需信任这台 Mac，并允许开发者模式/自动化。",
        "common.close": "关闭",
        "common.noUDID": "未映射 UDID",
        "common.notSet": "未设置",
        "common.default": "默认",
        "common.cancel": "取消",
        "mirror.pause": "暂停镜像",
        "mirror.start": "开始镜像",
        "mirror.disconnectControl": "断开控制",
        "mirror.home": "主屏幕",
        "mirror.appSwitcher": "App 切换器",
        "mirror.back": "返回",
        "mirror.pasteClipboard": "粘贴剪贴板",
        "mirror.close": "关闭镜像",
        "mirror.floatOnTop": "保持置顶",
        "mirror.size": "窗口尺寸",
        "mirror.size.small": "小",
        "mirror.size.medium": "中",
        "mirror.size.large": "大",
        "mirror.reconnectingBody": "镜像窗口已关闭。同一台设备重新连接后会在这里恢复可用。",
        "status.ready": "就绪",
        "status.deviceConnectedRefreshing": "设备已连接，正在刷新...",
        "status.deviceDisconnectedRefreshing": "设备已断开，正在刷新...",
        "status.permissionRequired": "需要相机权限，因为 iPhone 屏幕源是通过 AVFoundation 暴露出来的。",
        "status.noSources": "没有发现 iPhone 屏幕源。请用 USB 连接 iPhone，必要时解锁并信任这台 Mac，然后刷新。",
        "status.foundOne": "发现 1 个 iPhone 屏幕源。",
        "status.foundMany": "发现 %d 个 iPhone 屏幕源。",
        "status.reconnecting": "正在等待 %d 台设备重连。",
        "status.reconnectingMany": "正在等待 %d 台设备重连。",
        "diagnostic.camera": "相机权限",
        "diagnostic.backend": "镜像后端",
        "diagnostic.detected": "已发现屏幕源",
        "diagnostic.reconnecting": "重连中的设备",
        "diagnostic.autoStart": "自动打开镜像",
        "diagnostic.appiumServer": "Appium 服务",
        "diagnostic.appiumService": "Appium 状态",
        "diagnostic.controlBundle": "控制 Bundle",
        "diagnostic.xcodeTeam": "Apple Team ID",
        "diagnostic.wdaBundle": "WDA Bundle",
        "diagnostic.libimobiledevice": "libimobiledevice",
        "diagnostic.mirror": "镜像",
        "diagnostic.control": "控制",
        "common.on": "开",
        "common.off": "关",
        "connection.connected": "已连接",
        "connection.disconnected": "重连中",
        "connection.unavailable": "不可用",
        "mirror.state.stopped": "已停止",
        "mirror.state.starting": "启动中",
        "mirror.state.running": "镜像中",
        "mirror.state.failed": "失败",
        "control.state.unavailable": "未连接控制",
        "control.state.connecting": "连接中",
        "control.state.ready": "控制就绪",
        "control.state.failed": "控制失败",
        "control.phase.appium": "启动服务",
        "control.phase.wda": "安装代理",
        "control.phase.screen": "读取屏幕",
        "control.error.unlockDevice": "请解锁 iPhone 并保持亮屏，然后重试安装/连接。",
        "control.error.developerMode": "请在 iPhone 上开启开发者模式，然后重试安装/连接。",
        "control.error.uiAutomation": "请为这台 iPhone 开启 UI Automation，然后重试安装/连接。",
        "control.error.trustDevice": "请在 iPhone 上信任这台 Mac，然后重新连接 USB 并重试。",
        "control.error.signing": "WDA 签名失败。请检查设置里的 Apple Team ID 和 WDA Bundle ID。",
        "control.error.wdaNotReady": "WebDriverAgent 没有就绪。请解锁 iPhone 后重试安装/连接。",
        "appium.state.unknown": "未知",
        "appium.state.checking": "检查中",
        "appium.state.starting": "启动中",
        "appium.state.running": "运行中",
        "appium.state.stopped": "已停止",
        "appium.state.missing": "未安装",
        "appium.state.failed": "失败",
        "auth.authorized": "已授权",
        "auth.notDetermined": "未决定",
        "auth.denied": "已拒绝",
        "auth.restricted": "受限",
        "auth.unknown": "未知"
    ]
}
