import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case system
    case zhHans
    case en

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .system:
            "System"
        case .zhHans:
            "中文"
        case .en:
            "English"
        }
    }

    var usesChinese: Bool {
        switch self {
        case .zhHans:
            true
        case .en:
            false
        case .system:
            Locale.preferredLanguages.first?.lowercased().hasPrefix("zh") == true
        }
    }
}

enum AppCopy {
    static func text(_ key: String, language: AppLanguage) -> String {
        if language.usesChinese, let value = zhHans[key] {
            return value
        }
        return en[key] ?? key
    }

    private static let en: [String: String] = [
        "app.name": "StupidMirror",
        "dashboard.subtitle": "Select a USB device, then open it as a standalone mirror window.",
        "toolbar.autoStart": "Auto-start",
        "toolbar.stop": "Stop",
        "toolbar.settings": "Settings",
        "toolbar.diagnostics": "Diagnostics",
        "toolbar.refresh": "Refresh",
        "metric.devices": "Devices",
        "metric.mirrorWindows": "Mirror windows",
        "metric.controlReady": "Control ready",
        "permission.title": "Camera Access for iPhone Video",
        "permission.body": "macOS exposes the USB iPhone screen as an AVFoundation capture source. Camera access is required for video mirroring.",
        "permission.body.notDetermined": "Click Request Camera Access, then allow StupidMirror in the macOS prompt. StupidMirror only asks after this explicit action.",
        "permission.body.denied": "Camera access is off or restricted. Open Camera Settings, enable StupidMirror, then return and recheck.",
        "permission.requestAccess": "Request Camera Access",
        "permission.openSettings": "Open Camera Settings",
        "permission.recheck": "Recheck Permission",
        "permission.requesting": "Waiting for macOS…",
        "permission.microphone.title": "Optional: iPhone Audio",
        "permission.microphone.body.notDetermined": "Video mirroring works without audio. Enable audio only if you want to hear the iPhone through this Mac.",
        "permission.microphone.body.denied": "Microphone access is off or restricted. Video remains available and StupidMirror will leave the audio track disconnected.",
        "permission.microphone.body.authorized": "iPhone audio is enabled for new mirror sessions.",
        "permission.microphone.requestAccess": "Enable Audio",
        "permission.microphone.openSettings": "Open Microphone Settings",
        "empty.title": "No iPhone Screen Sources",
        "empty.body": "Connect an iPhone over USB, trust this Mac, unlock once if needed, then refresh.",
        "status.controlPreparing": "Preparing local control service...",
        "status.controlPreparingAgent": "Preparing control agent on this iPhone...",
        "status.controlNoUDID": "Control needs a mapped iPhone UDID. Reconnect the iPhone and trust this Mac.",
        "status.controlSetupRequired": "Control setup is incomplete. Follow the setup guide, then try again.",
        "status.controlAppiumUnavailable": "Mirroring still works. Control could not start; open Diagnostics for the cause and next step.",
        "status.controlOpenDiagnostics": "View Diagnostics",
        "control.setup.title": "Set Up iPhone Control",
        "control.setup.subtitle": "StupidMirror reuses an existing control agent first and only prepares signing when installation is required.",
        "control.setup.step1.title": "Connect and unlock the iPhone",
        "control.setup.step1.body": "Connect by USB and tap Trust if the iPhone asks whether to trust this Mac.",
        "control.setup.step2.title": "Enable automation on iPhone",
        "control.setup.step2.body": "Enable Settings > Privacy & Security > Developer Mode, restart if prompted, then enable Settings > Developer > Enable UI Automation.",
        "control.setup.step3.title": "First installation only: prepare signing",
        "control.setup.step3.body": "StupidMirror detects the Apple Development account on this Mac automatically. If none is found, sign in once in Xcode > Settings > Accounts, then detect again.",
        "control.setup.step4.body": "Signing is prepared automatically only when a control agent must be installed.",
        "control.setup.detectAccount": "Detect Again",
        "control.setup.chooseAccount": "Choose an Apple development account",
        "control.setup.chooseAccountPlaceholder": "Select an account",
        "control.setup.accountReady": "Apple development account detected",
        "control.setup.accountConfigured": "Signing account configured",
        "control.setup.accountMissing": "No Apple development account detected",
        "control.setup.manualEntry": "Can't detect it? Enter Team ID manually",
        "control.setup.manualEntryHelp": "Optional fallback. Enter the 10-character Team ID for the Apple account signed in to Xcode.",
        "control.setup.mirrorNote": "iPhone control is optional. Video mirroring continues to work even when these steps are incomplete.",
        "control.setup.retry": "Detect and Try Again",
        "menu.showDashboard": "Show Dashboard",
        "menu.refreshDevices": "Refresh Devices",
        "menu.devices": "Devices",
        "menu.noDevices": "No iPhone screen sources",
        "menu.openAll": "Open All Devices",
        "menu.stopAll": "Stop All Mirrors",
        "menu.quit": "Quit StupidMirror",
        "menu.open": "Open",
        "menu.live": "Live",
        "menu.reconnecting": "Reconnecting",
        "license.menu": "License & Activation…",
        "license.section": "License & Activation",
        "license.activation.title": "Activate StupidMirror",
        "license.activation.subtitle": "The 3-day trial starts when a mirror successfully runs for the first time.",
        "license.code": "Activation code",
        "license.code.placeholder": "SM-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX",
        "license.code.help": "Spaces and hyphens are ignored. Activation requires an internet connection.",
        "license.activate": "Activate",
        "license.activating": "Activating…",
        "license.openActivation": "Enter Activation Code…",
        "license.badge.unactivated": "Not activated",
        "license.badge.help": "Not activated. Click to enter an activation code.",
        "license.purchase.title": "Buy through Xiaohongshu",
        "license.purchase.placeholder": "QR code placeholder — the purchase channel is not online yet.",
        "license.status.checking": "Checking license…",
        "license.status.trialNotStarted": "3-day trial available",
        "license.status.trial": "Trial active",
        "license.status.expired": "Trial expired",
        "license.status.licensed": "Activated",
        "license.status.unavailable": "License unavailable",
        "license.status.expires": "Expires %@",
        "license.status.trialStartsOnMirror": "The timer begins only after a mirror starts successfully.",
        "license.error.notConfigured": "Activation is not configured in this build. Download the official GitHub release.",
        "license.error.invalid": "This activation code is invalid, unavailable, or already used.",
        "license.error.rateLimited": "Too many activation attempts. Please wait and try again.",
        "license.error.revoked": "This license has been revoked.",
        "card.defaultSubtitle": "iOS screen source",
        "card.ready": "Ready to mirror",
        "card.open": "Mirror window is open",
        "card.reconnecting": "Waiting for device",
        "card.thumbnailFresh": "Latest snapshot. Click to open a standalone mirror window.",
        "card.thumbnailLoading": "Capturing a fresh thumbnail...",
        "card.thumbnailUnavailable": "Thumbnail unavailable",
        "card.openMirror": "Open Mirror",
        "card.stopMirror": "Stop Mirror",
        "card.connectControl": "Connect Control",
        "card.installControlAgent": "Connect Control",
        "card.refreshThumbnail": "Refresh Thumbnail",
        "card.openButton": "Open",
        "card.closeButton": "Close",
        "card.waitingButton": "Waiting",
        "detail.selectTitle": "Select a Device",
        "detail.selectBody": "Pick an iPhone from the sidebar to see its screen and open a mirror window.",
        "detail.openMirror": "Open Mirror Window",
        "detail.closeMirror": "Close Mirror Window",
        "detail.control": "Control",
        "detail.connectControl": "Connect",
        "detail.installControlAgent": "Connect Control",
        "detail.disconnectControl": "Disconnect",
        "detail.controlHelp": "Optional: control the iPhone from this Mac. Mirroring works without it.",
        "detail.lastSnapshot": "Live snapshot",
        "settings.subtitle": "Mirror startup and advanced control-agent settings.",
        "settings.language": "Language",
        "settings.mirroring": "Mirroring",
        "settings.autoOpen": "Open mirror windows automatically when new devices appear",
        "settings.control": "Control",
        "settings.appiumURL": "Appium server URL",
        "settings.bundleID": "Bundle ID to launch",
        "settings.xcodeTeam": "Apple Team ID",
        "settings.xcodeSigningID": "Signing identity",
        "settings.controlAdvanced": "Advanced control settings",
        "settings.wdaBundleID": "WDA bundle ID",
        "settings.usePrebuiltWDA": "Reuse prebuilt WDA",
        "settings.check": "Check",
        "settings.startAppium": "Start Appium",
        "settings.stop": "Stop",
        "settings.appiumHelp": "Connect Control first reuses an existing agent. For a first installation, StupidMirror automatically detects the Apple Development account on this Mac; manual Team ID entry is only an advanced fallback.",
        "settings.general": "General",
        "toolbar.mcp": "Open MCP automation settings",
        "mcp.title": "MCP Automation",
        "mcp.server": "Local MCP Server",
        "mcp.enabled": "Start MCP server automatically",
        "mcp.clients": "%d clients",
        "mcp.port": "Port",
        "mcp.applyPort": "Apply and Restart",
        "mcp.localOnly": "Only 127.0.0.1 can connect; the port never falls back automatically.",
        "mcp.token": "Bearer Token",
        "mcp.show": "Show",
        "mcp.hide": "Hide",
        "mcp.copyToken": "Copy Token",
        "mcp.rotateToken": "Rotate Token",
        "mcp.tokenHelp": "Treat this token like a password. Rotation immediately disconnects old configurations.",
        "mcp.rotateConfirm": "Rotate the MCP token? Existing Codex and Claude configurations will stop working immediately.",
        "mcp.connect": "Connect Codex or Claude Code",
        "mcp.codexSteps": "Add this block to ~/.codex/config.toml, restart Codex, then run /mcp and verify that stupidmirror is connected. Remove the [mcp_servers.stupidmirror] block to disconnect it.",
        "mcp.claudeSteps": "Run this command in Terminal, restart Claude Code, then run /mcp and verify stupidmirror. To remove it later, run: claude mcp remove --scope user stupidmirror",
        "mcp.copyConfig": "Copy",
        "mcp.verify": "Keep StupidMirror open while using MCP. Start by listing devices; connect control before taps or gestures.",
        "mcp.testPrompt": "List the iPhones, connect control, take a screenshot, and tap the Settings icon.",
        "mcp.logs": "Recent Calls (sanitized)",
        "mcp.noLogs": "No MCP tools have been called yet.",
        "mcp.error": "MCP Error",
        "mcp.invalidPort": "Enter a port between 1024 and 65535.",
        "mcp.status.stopped": "Stopped",
        "mcp.status.starting": "Starting",
        "mcp.status.running": "Running",
        "mcp.status.failed": "Failed",
        "diagnostics.runtime": "Runtime",
        "diagnostics.devices": "Devices",
        "diagnostics.noDevices": "No AVFoundation .muxed iPhone screen source is currently visible.",
        "diagnostics.controlPrereq": "Control prerequisites",
        "diagnostics.controlHelp": "Mirroring needs no action. For optional control: 1. Trust this Mac on iPhone. 2. Enable Settings > Privacy & Security > Developer Mode and restart if prompted. 3. Enable Settings > Developer > Enable UI Automation. 4. Sign in to Xcode, enter the Apple Team ID in StupidMirror Settings, then click Connect Control.",
        "common.close": "Close",
        "common.noUDID": "No UDID mapped",
        "common.notSet": "Not set",
        "common.default": "Default",
        "common.cancel": "Cancel",
        "mirror.pause": "Pause Mirror",
        "mirror.start": "Start Mirror",
        "mirror.disconnectControl": "Disconnect Control",
        "mirror.home": "Home",
        "mirror.appSwitcher": "App Switcher",
        "mirror.back": "Back",
        "mirror.pasteClipboard": "Paste Clipboard",
        "mirror.close": "Close Mirror",
        "mirror.floatOnTop": "Keep on Top",
        "mirror.size": "Window Size",
        "mirror.size.small": "Small",
        "mirror.size.medium": "Medium",
        "mirror.size.large": "Large",
        "mirror.reconnectingBody": "The mirror window was closed. The device will become available here when it reconnects.",
        "status.ready": "Ready",
        "status.deviceConnectedRefreshing": "Device connected. Refreshing...",
        "status.deviceDisconnectedRefreshing": "Device disconnected. Refreshing...",
        "status.permissionRequired": "Camera permission is required because iPhone screen sources are exposed through AVFoundation.",
        "status.noSources": "No iPhone screen sources found. Connect an iPhone by USB, unlock it if needed, trust this Mac, then refresh.",
        "status.foundOne": "Found 1 iPhone screen source.",
        "status.foundMany": "Found %d iPhone screen sources.",
        "status.reconnecting": "Waiting for %d device to reconnect.",
        "status.reconnectingMany": "Waiting for %d devices to reconnect.",
        "diagnostic.camera": "Camera permission",
        "diagnostic.microphone": "Microphone permission",
        "diagnostic.backend": "Mirror backend",
        "diagnostic.detected": "Detected screen sources",
        "diagnostic.reconnecting": "Reconnecting devices",
        "diagnostic.autoStart": "Auto-start mirrors",
        "diagnostic.appiumServer": "Appium server",
        "diagnostic.appiumService": "Local Appium service (not device control)",
        "diagnostic.appiumDetail": "Appium detail",
        "diagnostic.deviceControlState": "iPhone WDA control",
        "diagnostic.controlBundle": "Control bundle",
        "diagnostic.xcodeTeam": "Apple Team ID",
        "diagnostic.wdaBundle": "WDA bundle",
        "diagnostic.libimobiledevice": "libimobiledevice",
        "diagnostic.mirror": "Mirror",
        "diagnostic.control": "Control",
        "common.on": "On",
        "common.off": "Off",
        "connection.connected": "Connected",
        "connection.disconnected": "Reconnecting",
        "connection.unavailable": "Unavailable",
        "mirror.state.stopped": "Stopped",
        "mirror.state.starting": "Starting",
        "mirror.state.running": "Live",
        "mirror.state.failed": "Failed",
        "control.state.unavailable": "Control not connected",
        "control.state.connecting": "Connecting",
        "control.state.connectingWDA": "Installing or connecting iPhone WDA",
        "control.state.ready": "Control ready",
        "control.state.failed": "Control failed",
        "control.phase.appium": "Starting service",
        "control.phase.wda": "Installing agent",
        "control.phase.screen": "Reading screen",
        "control.error.unlockDevice": "Unlock iPhone and keep it awake, then retry Install / Connect.",
        "control.error.developerMode": "Enable Developer Mode on iPhone, then retry Install / Connect.",
        "control.error.uiAutomation": "Enable UI Automation for this iPhone, then retry Install / Connect.",
        "control.error.trustDevice": "Trust this Mac on iPhone, then reconnect USB and retry.",
        "control.error.signing": "WDA signing failed. Check Apple Team ID and WDA bundle ID in Settings.",
        "control.error.signingSetupRequired": "No reusable control agent was found. First-time installation needs an Apple Development account on this Mac.",
        "control.error.wdaNotReady": "WebDriverAgent did not become ready. Unlock iPhone and retry Install / Connect.",
        "appium.state.unknown": "Unknown",
        "appium.state.checking": "Checking",
        "appium.state.starting": "Starting",
        "appium.state.running": "Running",
        "appium.state.stopped": "Stopped",
        "appium.state.missing": "Missing",
        "appium.state.failed": "Failed",
        "auth.authorized": "Authorized",
        "auth.notDetermined": "Not determined",
        "auth.denied": "Denied",
        "auth.restricted": "Restricted",
        "auth.unknown": "Unknown"
    ]

    private static let zhHans: [String: String] = [
        "app.name": "StupidMirror",
        "dashboard.subtitle": "选择 USB 设备，然后用独立镜像窗口打开。",
        "toolbar.autoStart": "自动打开",
        "toolbar.stop": "停止",
        "toolbar.settings": "设置",
        "toolbar.diagnostics": "诊断",
        "toolbar.refresh": "刷新",
        "metric.devices": "设备",
        "metric.mirrorWindows": "镜像窗口",
        "metric.controlReady": "控制就绪",
        "permission.title": "需要相机权限才能显示 iPhone 画面",
        "permission.body": "macOS 会把 USB iPhone 屏幕暴露成 AVFoundation 采集源，因此视频镜像必须使用相机权限。",
        "permission.body.notDetermined": "点击“请求相机权限”，再在 macOS 弹窗中允许 StupidMirror。只有你明确点击后，应用才会发起请求。",
        "permission.body.denied": "相机权限已关闭或受限。请打开相机权限设置并启用 StupidMirror，然后返回重新检查。",
        "permission.requestAccess": "请求相机权限",
        "permission.openSettings": "打开相机权限设置",
        "permission.recheck": "重新检查权限",
        "permission.requesting": "正在等待 macOS…",
        "permission.microphone.title": "可选：播放 iPhone 声音",
        "permission.microphone.body.notDetermined": "不授权也能继续使用视频镜像。只有需要从 Mac 听到 iPhone 声音时，才启用音频。",
        "permission.microphone.body.denied": "麦克风权限已关闭或受限。视频仍可正常使用，StupidMirror 不会接入音轨。",
        "permission.microphone.body.authorized": "新打开的镜像会播放 iPhone 声音。",
        "permission.microphone.requestAccess": "启用音频",
        "permission.microphone.openSettings": "打开麦克风权限设置",
        "empty.title": "没有发现 iPhone 屏幕源",
        "empty.body": "用 USB 连接 iPhone，信任这台 Mac，必要时先解锁一次，然后刷新。",
        "status.controlPreparing": "正在准备本机控制服务...",
        "status.controlPreparingAgent": "正在为这台 iPhone 准备控制代理...",
        "status.controlNoUDID": "控制需要匹配到 iPhone UDID。请重新连接 iPhone，并在手机上信任这台 Mac。",
        "status.controlSetupRequired": "控制功能尚未配置，请按弹出的操作指南完成后重试。",
        "status.controlAppiumUnavailable": "镜像仍可正常使用。控制启动失败，请查看诊断了解原因和下一步。",
        "status.controlOpenDiagnostics": "查看诊断",
        "control.setup.title": "设置 iPhone 控制功能",
        "control.setup.subtitle": "StupidMirror 会优先复用已有控制代理，确实需要安装时才准备签名。",
        "control.setup.step1.title": "连接并解锁 iPhone",
        "control.setup.step1.body": "使用 USB 连接；手机询问是否信任这台 Mac 时，点击“信任”。",
        "control.setup.step2.title": "在 iPhone 开启自动化",
        "control.setup.step2.body": "打开“设置 > 隐私与安全性 > 开发者模式”，按提示重启；然后打开“设置 > 开发者 > Enable UI Automation”。",
        "control.setup.step3.title": "仅首次安装：准备签名",
        "control.setup.step3.body": "StupidMirror 会自动检测这台 Mac 上的 Apple 开发账号。若未检测到，只需在 Xcode > Settings > Accounts 登录一次，再重新检测。",
        "control.setup.step4.body": "只有确实需要安装控制代理时，才会自动准备签名。",
        "control.setup.detectAccount": "重新检测",
        "control.setup.chooseAccount": "选择 Apple 开发账号",
        "control.setup.chooseAccountPlaceholder": "请选择账号",
        "control.setup.accountReady": "已检测到 Apple 开发账号",
        "control.setup.accountConfigured": "已配置签名账号",
        "control.setup.accountMissing": "未检测到 Apple 开发账号",
        "control.setup.manualEntry": "无法自动检测？手动输入 Team ID",
        "control.setup.manualEntryHelp": "可选备用方式：填写 Xcode 中已登录 Apple 账号对应的 10 位 Team ID。",
        "control.setup.mirrorNote": "控制功能是可选的。即使尚未完成这些步骤，视频镜像仍可正常使用。",
        "control.setup.retry": "检测并重新连接",
        "menu.showDashboard": "显示控制台",
        "menu.refreshDevices": "刷新设备",
        "menu.devices": "设备",
        "menu.noDevices": "没有 iPhone 屏幕源",
        "menu.openAll": "打开全部设备",
        "menu.stopAll": "停止所有镜像",
        "menu.quit": "退出 StupidMirror",
        "menu.open": "打开",
        "menu.live": "镜像中",
        "menu.reconnecting": "重连中",
        "license.menu": "许可与激活…",
        "license.section": "许可与激活",
        "license.activation.title": "激活 StupidMirror",
        "license.activation.subtitle": "3 天试用会在镜像第一次真正成功运行时开始计时。",
        "license.code": "激活码",
        "license.code.placeholder": "SM-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX",
        "license.code.help": "空格和短横线会自动忽略；激活时需要联网。",
        "license.activate": "激活",
        "license.activating": "正在激活…",
        "license.openActivation": "输入激活码…",
        "license.badge.unactivated": "未激活",
        "license.badge.help": "尚未激活，点击输入激活码。",
        "license.purchase.title": "通过小红书购买",
        "license.purchase.placeholder": "二维码占位——购买渠道暂未上线。",
        "license.status.checking": "正在检查许可…",
        "license.status.trialNotStarted": "可试用 3 天",
        "license.status.trial": "试用中",
        "license.status.expired": "试用已到期",
        "license.status.licensed": "已激活",
        "license.status.unavailable": "许可状态不可用",
        "license.status.expires": "到期时间：%@",
        "license.status.trialStartsOnMirror": "只有镜像成功启动后才会开始计时。",
        "license.error.notConfigured": "此构建未配置激活服务，请下载 GitHub 官方版本。",
        "license.error.invalid": "激活码无效、不可用或已经被使用。",
        "license.error.rateLimited": "尝试次数过多，请稍后再试。",
        "license.error.revoked": "此许可已被撤销。",
        "card.defaultSubtitle": "iOS 屏幕源",
        "card.ready": "可以开始镜像",
        "card.open": "镜像窗口已打开",
        "card.reconnecting": "等待设备重连",
        "card.thumbnailFresh": "最新缩略图。点击打开独立镜像窗口。",
        "card.thumbnailLoading": "正在捕获缩略图...",
        "card.thumbnailUnavailable": "缩略图不可用",
        "card.openMirror": "打开镜像",
        "card.stopMirror": "停止镜像",
        "card.connectControl": "连接控制",
        "card.installControlAgent": "连接控制",
        "card.refreshThumbnail": "刷新缩略图",
        "card.openButton": "打开",
        "card.closeButton": "关闭",
        "card.waitingButton": "等待中",
        "detail.selectTitle": "选择一台设备",
        "detail.selectBody": "在左侧选择一台 iPhone，查看画面并打开镜像窗口。",
        "detail.openMirror": "打开镜像窗口",
        "detail.closeMirror": "关闭镜像窗口",
        "detail.control": "控制",
        "detail.connectControl": "连接",
        "detail.installControlAgent": "连接控制",
        "detail.disconnectControl": "断开",
        "detail.controlHelp": "可选：从这台 Mac 控制 iPhone。不连接也可正常镜像。",
        "detail.lastSnapshot": "实时快照",
        "settings.subtitle": "镜像启动和高级控制代理配置。",
        "settings.language": "语言",
        "settings.mirroring": "镜像",
        "settings.autoOpen": "新设备出现时自动打开镜像窗口",
        "settings.control": "控制",
        "settings.appiumURL": "Appium 服务地址",
        "settings.bundleID": "启动的 Bundle ID",
        "settings.xcodeTeam": "Apple Team ID",
        "settings.xcodeSigningID": "签名身份",
        "settings.controlAdvanced": "高级控制设置",
        "settings.wdaBundleID": "WDA Bundle ID",
        "settings.usePrebuiltWDA": "复用已构建的 WDA",
        "settings.check": "检查",
        "settings.startAppium": "启动 Appium",
        "settings.stop": "停止",
        "settings.appiumHelp": "“连接控制”会先复用已有代理。首次安装时，StupidMirror 会自动检测这台 Mac 上的 Apple 开发账号；手填 Team ID 仅作为高级备用方式。",
        "settings.general": "常规",
        "toolbar.mcp": "打开 MCP 自动化设置",
        "mcp.title": "MCP 自动化",
        "mcp.server": "本机 MCP Server",
        "mcp.enabled": "自动启动 MCP Server",
        "mcp.clients": "%d 个客户端",
        "mcp.port": "端口",
        "mcp.applyPort": "应用并重启",
        "mcp.localOnly": "仅允许 127.0.0.1 访问；端口冲突时不会自动换端口。",
        "mcp.token": "Bearer Token",
        "mcp.show": "显示",
        "mcp.hide": "隐藏",
        "mcp.copyToken": "复制 Token",
        "mcp.rotateToken": "轮换 Token",
        "mcp.tokenHelp": "请把 Token 当作密码保管。轮换后，旧的 Codex 和 Claude 配置会立即失效。",
        "mcp.rotateConfirm": "确定轮换 MCP Token？现有 Codex 和 Claude 配置会立即失效。",
        "mcp.connect": "连接 Codex 或 Claude Code",
        "mcp.codexSteps": "把下面配置加入 ~/.codex/config.toml，重启 Codex，再运行 /mcp 确认 stupidmirror 已连接。删除 [mcp_servers.stupidmirror] 配置块即可移除。",
        "mcp.claudeSteps": "在终端执行下面命令，重启 Claude Code，再运行 /mcp 确认 stupidmirror。以后可运行 claude mcp remove --scope user stupidmirror 删除。",
        "mcp.copyConfig": "复制",
        "mcp.verify": "使用 MCP 时保持 StupidMirror 打开。先列出设备，点击或手势操作前先连接控制。",
        "mcp.testPrompt": "列出 iPhone，连接控制，截图并点击设置图标。",
        "mcp.logs": "最近调用（已脱敏）",
        "mcp.noLogs": "还没有 MCP 工具调用记录。",
        "mcp.error": "MCP 错误",
        "mcp.invalidPort": "请输入 1024 到 65535 之间的端口。",
        "mcp.status.stopped": "已停止",
        "mcp.status.starting": "启动中",
        "mcp.status.running": "运行中",
        "mcp.status.failed": "失败",
        "diagnostics.runtime": "运行时",
        "diagnostics.devices": "设备",
        "diagnostics.noDevices": "当前没有可见的 AVFoundation .muxed iPhone 屏幕源。",
        "diagnostics.controlPrereq": "控制前置条件",
        "diagnostics.controlHelp": "只镜像无需操作。如需控制：1. 在 iPhone 上信任这台 Mac；2. 打开“设置 > 隐私与安全性 > 开发者模式”，按提示重启；3. 打开“设置 > 开发者 > Enable UI Automation”；4. 在 Xcode 登录账号，在 StupidMirror 设置填入 Apple Team ID，再点“连接控制”。",
        "common.close": "关闭",
        "common.noUDID": "未映射 UDID",
        "common.notSet": "未设置",
        "common.default": "默认",
        "common.cancel": "取消",
        "mirror.pause": "暂停镜像",
        "mirror.start": "开始镜像",
        "mirror.disconnectControl": "断开控制",
        "mirror.home": "主屏幕",
        "mirror.appSwitcher": "App 切换器",
        "mirror.back": "返回",
        "mirror.pasteClipboard": "粘贴剪贴板",
        "mirror.close": "关闭镜像",
        "mirror.floatOnTop": "保持置顶",
        "mirror.size": "窗口尺寸",
        "mirror.size.small": "小",
        "mirror.size.medium": "中",
        "mirror.size.large": "大",
        "mirror.reconnectingBody": "镜像窗口已关闭。同一台设备重新连接后会在这里恢复可用。",
        "status.ready": "就绪",
        "status.deviceConnectedRefreshing": "设备已连接，正在刷新...",
        "status.deviceDisconnectedRefreshing": "设备已断开，正在刷新...",
        "status.permissionRequired": "需要相机权限，因为 iPhone 屏幕源是通过 AVFoundation 暴露出来的。",
        "status.noSources": "没有发现 iPhone 屏幕源。请用 USB 连接 iPhone，必要时解锁并信任这台 Mac，然后刷新。",
        "status.foundOne": "发现 1 个 iPhone 屏幕源。",
        "status.foundMany": "发现 %d 个 iPhone 屏幕源。",
        "status.reconnecting": "正在等待 %d 台设备重连。",
        "status.reconnectingMany": "正在等待 %d 台设备重连。",
        "diagnostic.camera": "相机权限",
        "diagnostic.microphone": "麦克风权限",
        "diagnostic.backend": "镜像后端",
        "diagnostic.detected": "已发现屏幕源",
        "diagnostic.reconnecting": "重连中的设备",
        "diagnostic.autoStart": "自动打开镜像",
        "diagnostic.appiumServer": "Appium 服务",
        "diagnostic.appiumService": "Appium 本机服务（不代表手机控制）",
        "diagnostic.appiumDetail": "Appium 详情",
        "diagnostic.deviceControlState": "iPhone WDA 控制状态",
        "diagnostic.controlBundle": "控制 Bundle",
        "diagnostic.xcodeTeam": "Apple Team ID",
        "diagnostic.wdaBundle": "WDA Bundle",
        "diagnostic.libimobiledevice": "libimobiledevice",
        "diagnostic.mirror": "镜像",
        "diagnostic.control": "控制",
        "common.on": "开",
        "common.off": "关",
        "connection.connected": "已连接",
        "connection.disconnected": "重连中",
        "connection.unavailable": "不可用",
        "mirror.state.stopped": "已停止",
        "mirror.state.starting": "启动中",
        "mirror.state.running": "镜像中",
        "mirror.state.failed": "失败",
        "control.state.unavailable": "未连接控制",
        "control.state.connecting": "连接中",
        "control.state.connectingWDA": "正在安装或连接手机 WDA",
        "control.state.ready": "控制就绪",
        "control.state.failed": "控制失败",
        "control.phase.appium": "启动服务",
        "control.phase.wda": "安装代理",
        "control.phase.screen": "读取屏幕",
        "control.error.unlockDevice": "请解锁 iPhone 并保持亮屏，然后重试安装/连接。",
        "control.error.developerMode": "请在 iPhone 上开启开发者模式，然后重试安装/连接。",
        "control.error.uiAutomation": "请为这台 iPhone 开启 UI Automation，然后重试安装/连接。",
        "control.error.trustDevice": "请在 iPhone 上信任这台 Mac，然后重新连接 USB 并重试。",
        "control.error.signing": "WDA 签名失败。请检查设置里的 Apple Team ID 和 WDA Bundle ID。",
        "control.error.signingSetupRequired": "未找到可复用的控制代理。首次安装需要这台 Mac 上存在 Apple 开发账号。",
        "control.error.wdaNotReady": "WebDriverAgent 没有就绪。请解锁 iPhone 后重试安装/连接。",
        "appium.state.unknown": "未知",
        "appium.state.checking": "检查中",
        "appium.state.starting": "启动中",
        "appium.state.running": "运行中",
        "appium.state.stopped": "已停止",
        "appium.state.missing": "未安装",
        "appium.state.failed": "失败",
        "auth.authorized": "已授权",
        "auth.notDetermined": "未决定",
        "auth.denied": "已拒绝",
        "auth.restricted": "受限",
        "auth.unknown": "未知"
    ]
}
