import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case system
    case zhHans
    case en

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .system:
            "System"
        case .zhHans:
            "中文"
        case .en:
            "English"
        }
    }

    var usesChinese: Bool {
        switch self {
        case .zhHans:
            true
        case .en:
            false
        case .system:
            Locale.preferredLanguages.first?.lowercased().hasPrefix("zh") == true
        }
    }
}

enum AppCopy {
    static func text(_ key: String, language: AppLanguage) -> String {
        if language.usesChinese, let value = zhHans[key] {
            return value
        }
        return en[key] ?? key
    }

    private static let en: [String: String] = [
        "dashboard.subtitle": "Select a connected device, then open it as a standalone mirror window.",
        "toolbar.autoStart": "Auto-start",
        "toolbar.audioPlayback": "Mac Audio",
        "toolbar.stop": "Stop",
        "toolbar.settings": "Settings",
        "toolbar.diagnostics": "Diagnostics",
        "toolbar.refresh": "Refresh",
        "toolbar.discoverWireless": "Wireless Discovery",
        "toolbar.discoverWirelessHelp": "Enable wireless mode and scan for iPhones previously paired over USB/Xcode.",
        "permission.title": "Camera Access for iPhone Video",
        "permission.body": "macOS exposes the USB iPhone screen as an AVFoundation capture source. Camera access is required for video mirroring.",
        "permission.body.notDetermined": "Click Request Camera Access, then allow StupidMirror in the macOS prompt. StupidMirror only asks after this explicit action.",
        "permission.body.denied": "Camera access is off or restricted. Open Camera Settings, enable StupidMirror, then return and recheck.",
        "permission.requestAccess": "Request Camera Access",
        "permission.openSettings": "Open Camera Settings",
        "permission.recheck": "Recheck Permission",
        "permission.requesting": "Waiting for macOS…",
        "permission.usbBanner.title": "USB mirroring needs Camera access",
        "permission.usbBanner.body": "Allow StupidMirror to show connected USB devices.",
        "permission.microphone.title": "Play iPhone Audio on This Mac",
        "permission.microphone.body.notDetermined": "Allow audio access to play iPhone sound on this Mac. Leave Mac Audio off to keep sound on the iPhone speaker.",
        "permission.microphone.body.denied": "Audio access is off or restricted. USB video still works, but the captured iPhone audio cannot play through this Mac.",
        "permission.microphone.body.authorized": "USB iPhone audio can play through this Mac.",
        "permission.microphone.requestAccess": "Enable Mac Audio",
        "permission.microphone.openSettings": "Open Microphone Settings",
        "empty.title": "No Supported Devices",
        "empty.body": "Connect an iPhone, or connect an Android 11+ device with USB debugging enabled, then refresh.",
        "status.controlPreparingAgent": "Preparing the control agent on this device...",
        "status.controlNoUDID": "Control needs a device identifier. Reconnect the device and approve trust or USB debugging.",
        "status.discoveringWireless": "Discovering paired wireless devices…",
        "agent.error.missingSigningTeam": "Select an Apple development team before preparing the iPhone agent.",
        "agent.error.missingRuntime": "The bundled device tunnel runtime is missing from this build.",
        "agent.error.setupRequired": "The screen agent is not installed on this iPhone. Connect it by USB and run the iPhone setup once.",
        "agent.error.buildFailed": "The screen agent could not be built or installed. Check the Apple account and signing settings, then retry.",
        "agent.error.launchFailed": "The screen agent could not be started on this iPhone. Retry; if it keeps failing, run the iPhone setup again.",
        "agent.error.deviceLocked": "Unlock the iPhone and keep its screen on, then retry.",
        "agent.error.developerModeDisabled": "Enable Developer Mode on the iPhone (Settings > Privacy & Security > Developer Mode), restart if asked, then retry.",
        "agent.error.deviceUnavailable": "The iPhone is not connected. Plug it in, or put it on the same Wi-Fi as this Mac.",
        "agent.error.wifiConnectionsUnavailable": "The iPhone is not reachable on the local network. Keep both devices on the same Wi-Fi; if this iPhone was never set up, run the iPhone setup over USB once.",
        "agent.error.developerImageMissing": "The iPhone's developer disk image is not mounted (it unmounts on reboot). Connect the iPhone by USB once, then retry.",
        "agent.error.timedOut": "The screen agent did not respond in time. Retry; if it keeps failing, reconnect USB.",
        "agent.error.automationNotApproved": "The iPhone did not allow automation. Unlock it, enter its passcode if it asks, then try again.",
        "iphone.setup.step.waitingForDevice": "Waiting for the iPhone: unlock it, and enter its passcode if it asks to allow automation…",
        "iphone.setup.cancelled": "iPhone preparation cancelled.",
        "iphone.setup.stop": "Stop",
        "iphone.setup.preparingOther": "Preparing %@…",
        "iphone.setup.developerMode.howTo": "On the iPhone: Settings > Privacy & Security > Developer Mode, turn it on, restart, and confirm. Then choose Check Again.",
        "iphone.setup.developerImage.missing": "Developer disk image not mounted yet (it is mounted automatically during preparation)",
        "iphone.setup.passcode.on": "Passcode set: the first launch after a restart asks for it on the iPhone",
        "agent.start.checkingAgent": "Checking the running screen agent…",
        "agent.start.checkingDevice": "Checking the iPhone…",
        "agent.start.launchingAgent": "Opening the device tunnel and starting the screen agent…",
        "agent.start.waitingForDevice": "Waiting for the iPhone: unlock it, and enter its passcode if it asks to allow automation…",
        "agent.start.connectingVideo": "Connecting the video stream…",
        "agent.start.retryingAgent": "The device tunnel changed. Retrying…",
        "agent.start.elapsed": "Elapsed %d s",
        "agent.start.cancel": "Cancel",
        "agent.start.retry": "Retry",
        "iphone.setup.title": "Set Up This iPhone",
        "iphone.setup.subtitle": "One USB preparation enables control over the cable and mirroring plus control over Wi-Fi.",
        "iphone.setup.open": "Open iPhone Setup…",
        "iphone.setup.step.usb.title": "Connect and unlock the iPhone",
        "iphone.setup.step.usb.body": "Connect by USB, tap Trust if the iPhone asks, and keep it unlocked.",
        "iphone.setup.usb.connected": "%@ is connected by USB.",
        "iphone.setup.usb.waiting": "Waiting for a USB iPhone.",
        "iphone.setup.step.developerMode.title": "Developer Mode",
        "iphone.setup.step.developerMode.body": "Settings > Privacy & Security > Developer Mode. The iPhone restarts once. The switch below is read from the iPhone.",
        "iphone.setup.developerMode.on": "Developer Mode is on.",
        "iphone.setup.developerMode.off": "Developer Mode is off. Turn it on, then recheck.",
        "iphone.setup.developerMode.unknown": "Connect the iPhone to read its Developer Mode state.",
        "iphone.setup.step.account.title": "Apple development account",
        "iphone.setup.step.account.body": "Signs the screen agent. StupidMirror uses an Apple account already signed in to Xcode on this Mac; a free account works.",
        "iphone.setup.step.agent.title": "Prepare the screen agent",
        "iphone.setup.step.agent.body": "Builds and installs the agent, test-launches it, and switches on the iPhone's Wi-Fi connections (the same switch as Xcode's \"Connect via network\"). Nothing on the iPhone needs tapping.",
        "iphone.setup.agent.installed": "Screen agent installed (iOS %@).",
        "iphone.setup.agent.notInstalled": "Screen agent not installed yet.",
        "iphone.setup.wifi.on": "Wi-Fi connections are on.",
        "iphone.setup.wifi.off": "Wi-Fi connections are off.",
        "iphone.setup.network.visible": "The iPhone is visible on the local network.",
        "iphone.setup.inspecting": "Reading the iPhone's state…",
        "iphone.setup.notPrepared": "Not prepared yet.",
        "iphone.setup.prepared": "This iPhone is prepared for USB and Wi-Fi.",
        "iphone.setup.preparing": "Preparing the iPhone…",
        "iphone.setup.ready": "iPhone setup completed.",
        "iphone.setup.ready.wifi": "Done. The agent launched over USB and the iPhone is visible on the local network.",
        "iphone.setup.ready.usbOnly": "Done over USB. The iPhone is not visible on the local network yet: check that it is on the same Wi-Fi as this Mac.",
        "iphone.setup.step.inspecting": "Reading the iPhone's state…",
        "iphone.setup.step.building": "Building the screen agent (first time takes 1–3 minutes)…",
        "iphone.setup.step.installing": "Installing the screen agent…",
        "iphone.setup.step.launching": "Test-launching the screen agent over USB…",
        "iphone.setup.step.enablingWiFi": "Switching on Wi-Fi connections…",
        "iphone.setup.step.verifyingNetwork": "Looking for the iPhone on the local network…",
        "iphone.setup.error.connectUSB": "Connect and unlock an iPhone by USB first.",
        "iphone.setup.prepare": "Prepare",
        "iphone.setup.reprepare": "Prepare Again",
        "iphone.setup.recheck": "Recheck",
        "iphone.setup.finish": "Done",
        "iphone.setup.note": "Mirroring over USB needs none of this. Control, and mirroring over Wi-Fi, use the agent prepared here.",
        "control.loading.startingAgent": "Opening the device tunnel and starting the screen agent",
        "control.loading.connectingAgent": "Connecting to the screen agent",
        "control.loading.expectation.agent": "Usually 5–10 seconds.",
        "control.loading.android.connectingAgent": "Starting UiAutomator2 on the phone",
        "detail.wirelessStarting": "Starting the screen agent…",
        "status.activationDeviceLimit": "Not activated: only one device can be mirrored at a time.",
        "status.activationControlRequired": "Activate StupidMirror to control more than one iPhone.",
        "status.controlAppiumUnavailable": "Mirroring still works. Control could not start; open Diagnostics for the cause and next step.",
        "status.controlOpenDiagnostics": "View Diagnostics",
        "control.setup.detectAccount": "Detect Again",
        "control.setup.chooseAccount": "Choose an Apple development account",
        "control.setup.chooseAccountPlaceholder": "Select an account",
        "control.setup.accountReady": "Apple development account detected",
        "control.setup.accountConfigured": "Signing account configured",
        "control.setup.accountMissing": "No Apple development account detected",
        "control.setup.manualEntry": "Can't detect it? Enter Team ID manually",
        "control.setup.manualEntryHelp": "Optional fallback. Enter the 10-character Team ID for the Apple account signed in to Xcode.",
        "menu.showDashboard": "Show Dashboard",
        "menu.refreshDevices": "Refresh Devices",
        "menu.devices": "Devices",
        "menu.noDevices": "No supported devices",
        "menu.openAll": "Open All Devices",
        "menu.stopAll": "Stop All Mirrors",
        "menu.quit": "Quit StupidMirror",
        "menu.open": "Open",
        "menu.live": "Live",
        "menu.reconnecting": "Reconnecting",
        "license.menu": "License & Account…",
        "license.section": "License & Account",
        "license.activation.title": "StupidMirror license",
        "license.activation.subtitle": "Mirroring and controlling one device is free without signing in. Multi-device features require an iTool login (Google, GitHub, or email), then an SM- code redeemed onto that account.",
        "license.code": "Activation code",
        "license.code.placeholder": "SM-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX",
        "license.code.help": "Sign in, buy an SM- code, then paste it here. Spaces and hyphens are ignored. iTool IT- codes are not accepted.",
        "license.redeem": "Redeem to account",
        "license.redeeming": "Redeeming…",
        "license.openActivation": "License & Account…",
        "license.badge.unactivated": "Not activated",
        "license.badge.help": "Not activated. Click to sign in and redeem an SM- code.",
        "license.purchase.title": "Buy on 链动小铺",
        "license.purchase.help": "Signed-in users buy a StupidMirror SM- code on 链动小铺, then paste it here to bind it to this iTool account. iTool Pro is a separate entitlement.",
        "license.purchase.online": "Buy activation code",
        "license.signIn.help": "Sign in with the same iTool account (Google, GitHub, or email) to buy, redeem, or claim a license. Free one-device mirroring keeps working while signed out.",
        "license.signIn.google": "Continue with Google",
        "license.signIn.github": "Continue with GitHub",
        "license.signIn.email": "Email",
        "license.signIn.password": "Password",
        "license.signIn.emailSubmit": "Sign in with email",
        "license.signedIn": "Signed in",
        "license.signOut": "Sign out",
        "license.claim": "Claim this Mac license",
        "license.claim.title": "Bind this Mac's license to your account",
        "license.claim.help": "This Mac still has a valid older receipt. Sign in and claim it so the license follows your account instead of this Mac installation.",
        "license.status.checking": "Checking license…",
        "license.status.unlicensed": "Not activated",
        "license.status.licensed": "Activated",
        "license.status.unavailable": "License unavailable",
        "license.capabilities.unactivated": "Free: mirror and control one device at a time, including USB and wireless.",
        "license.capabilities.activated": "Activated: mirror and control multiple devices at once.",
        "license.capabilities.account": "Activated on this iTool account: mirror and control multiple devices at once.",
        "license.capabilities.needsClaim": "This Mac is still licensed from an older receipt. Sign in and claim it so the license is bound to your account.",
        "license.capabilities.checking": "Mirroring remains available while the license is checked.",
        "license.error.notConfigured": "Activation is not configured in this build. Download the official GitHub release.",
        "license.error.invalid": "This activation code is invalid, unavailable, or already used.",
        "license.error.rateLimited": "Too many activation attempts. Please wait and try again.",
        "license.error.revoked": "This license has been revoked.",
        "license.error.storage": "License record unavailable.",
        "license.error.loginRequired": "Sign in with Google, GitHub, or email to buy, redeem, or claim a license.",
        "license.error.alreadyLicensed": "This account already has an active StupidMirror license.",
        "license.error.alreadyClaimed": "This activation is already bound to another account.",
        "license.error.claimRequired": "Sign in and claim this Mac license to your account to keep multi-device features.",
        "license.error.itool": "iTool Pro codes cannot be redeemed in StupidMirror. Buy and paste an SM- code.",
        "card.openMirror": "Open Mirror",
        "card.stopMirror": "Stop Mirror",
        "card.installControlAgent": "Connect Control",
        "card.refreshThumbnail": "Refresh Thumbnail",
        "detail.selectTitle": "Select a Device",
        "detail.wirelessStopped": "Open the mirror to start the wireless screen.",
        "detail.selectBody": "Pick a device from the sidebar to see its screen and open a mirror window.",
        "detail.openMirror": "Open Mirror Window",
        "detail.closeMirror": "Close Mirror Window",
        "detail.installControlAgent": "Connect Control",
        "detail.disconnectControl": "Disconnect",
        "detail.controlHelp": "Optional: control this device from the Mac. Mirroring works without it.",
        "detail.controlActivationHelp": "Activate to control this device. Mirroring remains available.",
        "device.actions": "Device actions",
        "device.remove": "Remove Device",
        "device.remove.title": "Remove this device?",
        "device.remove.message": "%@ will be removed from this list. It will appear again after reconnecting.",
        "settings.subtitle": "Mirror startup and advanced control-agent settings.",
        "settings.language": "Language",
        "settings.mirroring": "Mirroring",
        "settings.audioPlayback": "Play Device Audio on Mac",
        "settings.audioPlaybackHelp": "USB iPhone mirroring always takes the phone speaker (same as QuickTime). Turn this on to hear that audio on this Mac (needs Microphone permission). Wireless iPhone keeps the phone speaker. Android: off keeps the phone speaker; on plays here, and Android 13+ also keeps the phone speaker.",
        "settings.autoOpen": "Open mirror windows automatically when new devices appear",
        "settings.wirelessMirroring": "Enable wireless mode",
        "settings.wirelessMirroringHelp": "Reaches paired iPhones over the same local network through a CoreDevice tunnel and runs WebDriverAgent on them. The first trust, signing, agent installation, and the Wi-Fi connections switch still require USB.",
        "transport.usb": "USB",
        "transport.adb": "ADB",
        "transport.wireless": "Wireless",
        "settings.control": "Control",
        "settings.appiumURL": "Appium server URL",
        "settings.bundleID": "Bundle ID to launch",
        "settings.xcodeTeam": "Apple Team ID",
        "settings.xcodeSigningID": "Signing identity",
        "settings.controlAdvanced": "Advanced control settings",
        "settings.wdaBundleID": "WDA bundle ID",
        "settings.check": "Check",
        "settings.startAppium": "Start Appium",
        "settings.stop": "Stop",
        "settings.appiumHelp": "Connect Control first reuses an existing agent. For a first installation, StupidMirror automatically detects the Apple Development account on this Mac; manual Team ID entry is only an advanced fallback.",
        "settings.general": "General",
        "toolbar.mcp": "Open MCP automation settings",
        "mcp.title": "MCP Automation",
        "mcp.server": "Local MCP Server",
        "mcp.enabled": "Start MCP server automatically",
        "mcp.clients": "%d clients",
        "mcp.port": "Port",
        "mcp.applyPort": "Apply and Restart",
        "mcp.localOnly": "Only 127.0.0.1 can connect; the port never falls back automatically.",
        "mcp.token": "Bearer Token",
        "mcp.show": "Show",
        "mcp.hide": "Hide",
        "mcp.copyToken": "Copy Token",
        "mcp.rotateToken": "Rotate Token",
        "mcp.tokenHelp": "Treat this token like a password. Rotation immediately disconnects old configurations.",
        "mcp.rotateConfirm": "Rotate the MCP token? Existing Codex and Claude configurations will stop working immediately.",
        "mcp.connect": "Connect Codex or Claude Code",
        "mcp.codexSteps": "Add this block to ~/.codex/config.toml, restart Codex, then run /mcp and verify that stupidmirror is connected. Remove the [mcp_servers.stupidmirror] block to disconnect it.",
        "mcp.claudeSteps": "Run this command in Terminal, restart Claude Code, then run /mcp and verify stupidmirror. To remove it later, run: claude mcp remove --scope user stupidmirror",
        "mcp.copyConfig": "Copy",
        "mcp.verify": "Keep StupidMirror open while using MCP. Start by listing devices; connect control before taps or gestures.",
        "mcp.testPrompt": "List the devices, connect control, take a screenshot, and tap the Settings icon.",
        "mcp.logs": "Recent Calls (sanitized)",
        "mcp.noLogs": "No MCP tools have been called yet.",
        "mcp.error": "MCP Error",
        "mcp.invalidPort": "Enter a port between 1024 and 65535.",
        "mcp.status.stopped": "Stopped",
        "mcp.status.starting": "Starting",
        "mcp.status.running": "Running",
        "mcp.status.failed": "Failed",
        "diagnostics.runtime": "Runtime",
        "diagnostics.devices": "Devices",
        "diagnostics.noDevices": "No supported iOS or Android device is currently visible.",
        "diagnostics.controlPrereq": "Control prerequisites",
        "diagnostics.controlHelp": "Android control needs USB debugging and installs UiAutomator2 helpers on first connect. iPhone control needs trust, Developer Mode, UI Automation, and an Apple signing team for WebDriverAgent.",
        "common.close": "Close",
        "common.noUDID": "No UDID mapped",
        "common.notSet": "Not set",
        "common.default": "Default",
        "common.cancel": "Cancel",
        "mirror.pause": "Pause Mirror",
        "mirror.start": "Start Mirror",
        "mirror.disconnectControl": "Disconnect Control",
        "mirror.home": "Home",
        "mirror.appSwitcher": "App Switcher",
        "mirror.back": "Back",
        "mirror.copyScreenshot": "Copy Screenshot",
        "mirror.screenshotCopied": "Screenshot Copied",
        "mirror.pasteClipboard": "Paste Clipboard",
        "mirror.close": "Close Mirror",
        "mirror.floatOnTop": "Keep on Top",
        "mirror.size": "Window Size",
        "mirror.size.small": "Small",
        "mirror.size.medium": "Medium",
        "mirror.size.large": "Large",
        "mirror.reconnectingBody": "The mirror window was closed. The device will become available here when it reconnects.",
        "status.ready": "Ready",
        "status.deviceConnectedRefreshing": "Device connected. Refreshing...",
        "status.deviceDisconnectedRefreshing": "Device disconnected. Refreshing...",
        "status.permissionRequired": "Camera permission is required because iPhone screen sources are exposed through AVFoundation.",
        "status.noSources": "No supported devices found. Connect an iPhone or an Android 11+ device with USB debugging, then refresh.",
        "status.foundOne": "Found 1 connected device.",
        "status.foundMany": "Found %d connected devices.",
        "status.reconnecting": "Waiting for %d device to reconnect.",
        "status.reconnectingMany": "Waiting for %d devices to reconnect.",
        "status.deviceRemoved": "%@ was removed. Reconnect it to show it again.",
        "diagnostic.camera": "Camera permission",
        "diagnostic.microphone": "Microphone permission",
        "diagnostic.backend": "Mirror backend",
        "diagnostic.detected": "Detected screen sources",
        "diagnostic.reconnecting": "Reconnecting devices",
        "diagnostic.autoStart": "Auto-start mirrors",
        "diagnostic.appiumServer": "Appium server",
        "diagnostic.appiumService": "Local Appium service (not device control)",
        "diagnostic.appiumDetail": "Appium detail",
        "diagnostic.deviceControlState": "Device Appium control",
        "diagnostic.controlBundle": "Control bundle",
        "diagnostic.xcodeTeam": "Apple Team ID",
        "diagnostic.wdaBundle": "WDA bundle",
        "diagnostic.libimobiledevice": "USB device metadata",
        "diagnostic.mirror": "Mirror",
        "diagnostic.control": "Control",
        "common.on": "On",
        "common.off": "Off",
        "connection.connected": "Connected",
        "connection.disconnected": "Reconnecting",
        "connection.unavailable": "Unavailable",
        "mirror.state.stopped": "Stopped",
        "mirror.state.starting": "Starting",
        "mirror.state.running": "Live",
        "mirror.state.failed": "Failed",
        "control.state.unavailable": "Control not connected",
        "control.state.activationRequired": "Control requires activation",
        "control.state.connecting": "Connecting",
        "control.state.connectingWDA": "Installing or connecting device control",
        "control.state.ready": "Control ready",
        "control.state.failed": "Control failed",
        "control.phase.appium": "Starting service",
        "control.phase.wda": "Installing agent",
        "control.phase.screen": "Reading screen",
        "control.loading.title": "Preparing iPhone control",
        "control.loading.finishing": "Finishing the control connection",
        "control.loading.expectation.short": "This usually takes a few seconds.",
        "control.loading.expectation.finishing": "Almost ready.",
        "control.loading.elapsed": "Elapsed %d:%02d",
        "control.loading.keepAwake": "Keep the iPhone unlocked and awake, and do not disconnect USB.",
        "control.loading.android.title": "Preparing Android control",
        "control.loading.android.finishing": "Finishing the Android control connection",
        "control.loading.android.expectation.agent": "The first connection usually takes 20–60 seconds; later connections are much faster.",
        "control.loading.android.keepAwake": "Keep Android unlocked and awake, leave USB connected, and approve any debugging prompt.",
        "control.error.appiumUnavailable": "The local control service could not start. Open Diagnostics and retry.",
        "control.error.unlockDevice": "Unlock iPhone and keep it awake, then retry Install / Connect.",
        "control.error.developerMode": "Enable Developer Mode on iPhone, then retry Install / Connect.",
        "control.error.uiAutomation": "Enable UI Automation for this iPhone, then retry Install / Connect.",
        "control.error.trustDevice": "Trust this Mac on iPhone, then reconnect USB and retry.",
        "control.error.signing": "WDA signing failed. Check Apple Team ID and WDA bundle ID in Settings.",
        "appium.state.unknown": "Unknown",
        "diagnostic.androidADB": "Android ADB",
        "diagnostic.androidMirror": "Android mirror runtime",
        "appium.state.checking": "Checking",
        "appium.state.starting": "Starting",
        "appium.state.running": "Running",
        "appium.state.stopped": "Stopped",
        "appium.state.missing": "Missing",
        "appium.state.failed": "Failed",
        "auth.authorized": "Authorized",
        "auth.notDetermined": "Not determined",
        "auth.denied": "Denied",
        "auth.restricted": "Restricted",
        "auth.unknown": "Unknown"
    ]

    private static let zhHans: [String: String] = [
        "dashboard.subtitle": "选择已连接设备，然后用独立镜像窗口打开。",
        "toolbar.autoStart": "自动打开",
        "toolbar.audioPlayback": "Mac 声音",
        "toolbar.stop": "停止",
        "toolbar.settings": "设置",
        "toolbar.diagnostics": "诊断",
        "toolbar.refresh": "刷新",
        "toolbar.discoverWireless": "无线发现",
        "toolbar.discoverWirelessHelp": "启用无线模式，并扫描之前已通过 USB/Xcode 配对的 iPhone。",
        "permission.title": "需要相机权限才能显示 iPhone 画面",
        "permission.body": "macOS 会把 USB iPhone 屏幕暴露成 AVFoundation 采集源，因此视频镜像必须使用相机权限。",
        "permission.body.notDetermined": "点击“请求相机权限”，再在 macOS 弹窗中允许 StupidMirror。只有你明确点击后，应用才会发起请求。",
        "permission.body.denied": "相机权限已关闭或受限。请打开相机权限设置并启用 StupidMirror，然后返回重新检查。",
        "permission.requestAccess": "请求相机权限",
        "permission.openSettings": "打开相机权限设置",
        "permission.recheck": "重新检查权限",
        "permission.requesting": "正在等待 macOS…",
        "permission.usbBanner.title": "USB 镜像需要相机权限",
        "permission.usbBanner.body": "允许 StupidMirror 后才会显示已连接的 USB 设备。",
        "permission.microphone.title": "在这台 Mac 上播放 iPhone 声音",
        "permission.microphone.body.notDetermined": "允许音频权限后，可在这台 Mac 上播放 iPhone 声音。关闭“Mac 声音”则继续从 iPhone 扬声器播放。",
        "permission.microphone.body.denied": "音频权限已关闭或受限。USB 画面仍可使用，但捕获到的 iPhone 声音无法从这台 Mac 播放。",
        "permission.microphone.body.authorized": "USB iPhone 声音可以从这台 Mac 播放。",
        "permission.microphone.requestAccess": "启用 Mac 声音",
        "permission.microphone.openSettings": "打开麦克风权限设置",
        "empty.title": "没有发现受支持的设备",
        "empty.body": "连接 iPhone，或连接已开启 USB 调试的 Android 11 及以上设备，然后刷新。",
        "status.controlPreparingAgent": "正在为当前设备准备控制代理...",
        "status.controlNoUDID": "控制需要设备标识。请重新连接设备，并按提示信任或允许 USB 调试。",
        "status.discoveringWireless": "正在发现已配对的无线设备…",
        "agent.error.missingSigningTeam": "请先选择 Apple 开发账号，再准备 iPhone 代理。",
        "agent.error.missingRuntime": "此构建缺少内置的设备隧道组件。",
        "agent.error.setupRequired": "这台 iPhone 上还没有安装屏幕代理。请用 USB 连接并运行一次 iPhone 设置。",
        "agent.error.buildFailed": "屏幕代理构建或安装失败。请检查 Apple 账号与签名设置后重试。",
        "agent.error.launchFailed": "无法在这台 iPhone 上启动屏幕代理。请重试；若持续失败，请重新运行 iPhone 设置。",
        "agent.error.deviceLocked": "请解锁 iPhone 并保持亮屏，然后重试。",
        "agent.error.developerModeDisabled": "请在 iPhone 上开启开发者模式（设置 > 隐私与安全性 > 开发者模式），按提示重启后重试。",
        "agent.error.deviceUnavailable": "iPhone 未连接。请插上数据线，或让它与这台 Mac 连接同一个 Wi‑Fi。",
        "agent.error.wifiConnectionsUnavailable": "在局域网上找不到这台 iPhone。请让两台设备连接同一个 Wi‑Fi；如果这台 iPhone 从未设置过，请先用 USB 运行一次 iPhone 设置。",
        "agent.error.developerImageMissing": "iPhone 的开发者磁盘映像尚未挂载（重启后会卸载）。请用 USB 连接一次 iPhone，然后重试。",
        "agent.error.timedOut": "屏幕代理没有及时响应。请重试；若持续失败，再重新连接 USB。",
        "agent.error.automationNotApproved": "iPhone 未允许自动化。请解锁手机，按提示输入锁屏密码后重试。",
        "iphone.setup.step.waitingForDevice": "正在等待 iPhone：请解锁；若提示允许自动化，请输入锁屏密码…",
        "iphone.setup.cancelled": "已取消准备 iPhone。",
        "iphone.setup.stop": "停止",
        "iphone.setup.preparingOther": "正在准备 %@…",
        "iphone.setup.developerMode.howTo": "在 iPhone 上打开“设置 > 隐私与安全性 > 开发者模式”，开启后按提示重启并确认，然后点“重新检查”。",
        "iphone.setup.developerImage.missing": "开发者磁盘映像尚未挂载（准备时会自动挂载）",
        "iphone.setup.passcode.on": "已设置锁屏密码：重启后首次启动时，iPhone 会要求输入密码",
        "agent.start.checkingAgent": "正在检查已运行的屏幕代理…",
        "agent.start.checkingDevice": "正在检查 iPhone…",
        "agent.start.launchingAgent": "正在建立设备隧道并启动屏幕代理…",
        "agent.start.waitingForDevice": "正在等待 iPhone：请解锁；若提示允许自动化，请输入锁屏密码…",
        "agent.start.connectingVideo": "正在连接视频流…",
        "agent.start.retryingAgent": "设备隧道发生变化，正在重试…",
        "agent.start.elapsed": "已等待 %d 秒",
        "agent.start.cancel": "取消",
        "agent.start.retry": "重试",
        "iphone.setup.title": "设置这台 iPhone",
        "iphone.setup.subtitle": "用 USB 准备一次，之后有线可以控制，Wi‑Fi 下可以镜像并控制。",
        "iphone.setup.open": "打开 iPhone 设置…",
        "iphone.setup.step.usb.title": "连接并解锁 iPhone",
        "iphone.setup.step.usb.body": "使用 USB 连接；手机询问是否信任时点“信任”，并保持解锁。",
        "iphone.setup.usb.connected": "%@ 已通过 USB 连接。",
        "iphone.setup.usb.waiting": "正在等待 USB iPhone。",
        "iphone.setup.step.developerMode.title": "开发者模式",
        "iphone.setup.step.developerMode.body": "设置 > 隐私与安全性 > 开发者模式。iPhone 会重启一次。下面的状态是从 iPhone 上实际读取的。",
        "iphone.setup.developerMode.on": "开发者模式已开启。",
        "iphone.setup.developerMode.off": "开发者模式未开启。开启后点“重新检查”。",
        "iphone.setup.developerMode.unknown": "连接 iPhone 后会读取开发者模式状态。",
        "iphone.setup.step.account.title": "Apple 开发账号",
        "iphone.setup.step.account.body": "用于给屏幕代理签名。StupidMirror 会使用这台 Mac 的 Xcode 中已登录的 Apple 账号，免费账号即可。",
        "iphone.setup.step.agent.title": "准备屏幕代理",
        "iphone.setup.step.agent.body": "构建并安装代理，试启动一次，然后开启 iPhone 的 Wi‑Fi 连接（与 Xcode 的“通过网络连接”是同一个开关）。手机上不需要点任何东西。",
        "iphone.setup.agent.installed": "屏幕代理已安装（iOS %@）。",
        "iphone.setup.agent.notInstalled": "屏幕代理尚未安装。",
        "iphone.setup.wifi.on": "Wi‑Fi 连接已开启。",
        "iphone.setup.wifi.off": "Wi‑Fi 连接未开启。",
        "iphone.setup.network.visible": "局域网上已能看到这台 iPhone。",
        "iphone.setup.inspecting": "正在读取 iPhone 状态…",
        "iphone.setup.notPrepared": "尚未准备。",
        "iphone.setup.prepared": "这台 iPhone 已准备好，USB 和 Wi‑Fi 均可使用。",
        "iphone.setup.preparing": "正在准备 iPhone…",
        "iphone.setup.ready": "iPhone 设置已完成。",
        "iphone.setup.ready.wifi": "完成。代理已通过 USB 启动，局域网上也能看到这台 iPhone。",
        "iphone.setup.ready.usbOnly": "USB 部分已完成。局域网上暂时看不到这台 iPhone：请确认它与这台 Mac 在同一个 Wi‑Fi。",
        "iphone.setup.step.inspecting": "正在读取 iPhone 状态…",
        "iphone.setup.step.building": "正在构建屏幕代理（首次需要 1–3 分钟）…",
        "iphone.setup.step.installing": "正在安装屏幕代理…",
        "iphone.setup.step.launching": "正在通过 USB 试启动屏幕代理…",
        "iphone.setup.step.enablingWiFi": "正在开启 Wi‑Fi 连接…",
        "iphone.setup.step.verifyingNetwork": "正在局域网上查找这台 iPhone…",
        "iphone.setup.error.connectUSB": "请先通过 USB 连接并解锁一台 iPhone。",
        "iphone.setup.prepare": "开始准备",
        "iphone.setup.reprepare": "重新准备",
        "iphone.setup.recheck": "重新检查",
        "iphone.setup.finish": "完成",
        "iphone.setup.note": "USB 镜像不需要这些步骤。控制功能，以及 Wi‑Fi 下的镜像，使用这里准备好的代理。",
        "control.loading.startingAgent": "正在建立设备隧道并启动屏幕代理",
        "control.loading.connectingAgent": "正在连接屏幕代理",
        "control.loading.expectation.agent": "通常需要 5–10 秒。",
        "control.loading.android.connectingAgent": "正在手机上启动 UiAutomator2",
        "detail.wirelessStarting": "正在启动屏幕代理…",
        "status.activationDeviceLimit": "未激活时只能同时镜像 1 台设备。",
        "status.activationControlRequired": "同时控制超过 1 台 iPhone 需要激活 StupidMirror。",
        "status.controlAppiumUnavailable": "镜像仍可正常使用。控制启动失败，请查看诊断了解原因和下一步。",
        "status.controlOpenDiagnostics": "查看诊断",
        "control.setup.detectAccount": "重新检测",
        "control.setup.chooseAccount": "选择 Apple 开发账号",
        "control.setup.chooseAccountPlaceholder": "请选择账号",
        "control.setup.accountReady": "已检测到 Apple 开发账号",
        "control.setup.accountConfigured": "已配置签名账号",
        "control.setup.accountMissing": "未检测到 Apple 开发账号",
        "control.setup.manualEntry": "无法自动检测？手动输入 Team ID",
        "control.setup.manualEntryHelp": "可选备用方式：填写 Xcode 中已登录 Apple 账号对应的 10 位 Team ID。",
        "menu.showDashboard": "显示控制台",
        "menu.refreshDevices": "刷新设备",
        "menu.devices": "设备",
        "menu.noDevices": "没有受支持的设备",
        "menu.openAll": "打开全部设备",
        "menu.stopAll": "停止所有镜像",
        "menu.quit": "退出 StupidMirror",
        "menu.open": "打开",
        "menu.live": "镜像中",
        "menu.reconnecting": "重连中",
        "license.menu": "许可与账号…",
        "license.section": "许可与账号",
        "license.activation.title": "StupidMirror 许可",
        "license.activation.subtitle": "未登录也可免费镜像和控制一台设备。多设备能力需要登录同一个 iTool 账号（Google / GitHub / 邮箱），再把 SM- 激活码兑换到该账号。",
        "license.code": "激活码",
        "license.code.placeholder": "SM-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX",
        "license.code.help": "先登录，再购买 SM- 激活码并粘贴到这里。空格和短横线会自动忽略。不接受 iTool 的 IT- 激活码。",
        "license.redeem": "兑换到账号",
        "license.redeeming": "正在兑换…",
        "license.openActivation": "许可与账号…",
        "license.badge.unactivated": "未激活",
        "license.badge.help": "尚未激活，点击登录并用 SM- 激活码兑换。",
        "license.purchase.title": "在链动小铺购买",
        "license.purchase.help": "登录后在链动小铺购买 StupidMirror 的 SM- 激活码，再粘贴到这里绑定到当前 iTool 账号。iTool Pro 是另一项权益。",
        "license.purchase.online": "购买激活码",
        "license.signIn.help": "使用同一个 iTool 账号（Google / GitHub / 邮箱）登录后才能购买、兑换或认领许可。未登录时仍可免费镜像一台设备。",
        "license.signIn.google": "使用 Google 继续",
        "license.signIn.github": "使用 GitHub 继续",
        "license.signIn.email": "邮箱",
        "license.signIn.password": "密码",
        "license.signIn.emailSubmit": "使用邮箱登录",
        "license.signedIn": "已登录",
        "license.signOut": "退出登录",
        "license.claim": "认领这台 Mac 的许可",
        "license.claim.title": "把这台 Mac 的许可绑定到账号",
        "license.claim.help": "这台 Mac 仍有一份有效的旧回执。登录并认领后，许可会跟随账号，而不再绑定这次 Mac 安装。",
        "license.status.checking": "正在检查许可…",
        "license.status.unlicensed": "未激活",
        "license.status.licensed": "已激活",
        "license.status.unavailable": "许可状态不可用",
        "license.capabilities.unactivated": "免费能力：可同时镜像和控制 1 台设备，USB、无线均可使用。",
        "license.capabilities.activated": "已激活：可同时镜像和控制多台设备。",
        "license.capabilities.account": "已绑定到当前 iTool 账号：可同时镜像和控制多台设备。",
        "license.capabilities.needsClaim": "这台 Mac 仍可凭旧回执使用。请登录并把许可认领到账号，以免日后失效。",
        "license.capabilities.checking": "检查许可期间不影响镜像使用。",
        "license.error.notConfigured": "此构建未配置激活服务，请下载 GitHub 官方版本。",
        "license.error.invalid": "激活码无效、不可用或已经被使用。",
        "license.error.rateLimited": "尝试次数过多，请稍后再试。",
        "license.error.revoked": "此许可已被撤销。",
        "license.error.storage": "许可记录不可用。",
        "license.error.loginRequired": "请使用 Google、GitHub 或邮箱登录后再购买、兑换或认领许可。",
        "license.error.alreadyLicensed": "此账号已有有效的 StupidMirror 许可。",
        "license.error.alreadyClaimed": "此激活已绑定到其他账号。",
        "license.error.claimRequired": "请登录并把这台 Mac 的许可认领到账号，才能继续使用多设备功能。",
        "license.error.itool": "不能在 StupidMirror 中兑换 iTool Pro 激活码。请购买并粘贴 SM- 激活码。",
        "card.openMirror": "打开镜像",
        "card.stopMirror": "停止镜像",
        "card.installControlAgent": "连接控制",
        "card.refreshThumbnail": "刷新缩略图",
        "detail.selectTitle": "选择一台设备",
        "detail.wirelessStopped": "打开镜像后显示无线画面。",
        "detail.selectBody": "在左侧选择一台设备，查看画面并打开镜像窗口。",
        "detail.openMirror": "打开镜像窗口",
        "detail.closeMirror": "关闭镜像窗口",
        "detail.installControlAgent": "连接控制",
        "detail.disconnectControl": "断开",
        "detail.controlHelp": "可选：从这台 Mac 控制当前设备。不连接也可正常镜像。",
        "detail.controlActivationHelp": "激活后才能控制当前设备；镜像不受影响。",
        "device.actions": "设备操作",
        "device.remove": "移除设备",
        "device.remove.title": "移除这台设备？",
        "device.remove.message": "%@ 将从当前列表移除，重新连接后会再次显示。",
        "settings.subtitle": "镜像启动和高级控制代理配置。",
        "settings.language": "语言",
        "settings.mirroring": "镜像",
        "settings.audioPlayback": "在 Mac 上播放设备声音",
        "settings.audioPlaybackHelp": "USB 连接 iPhone 时，iOS 会把声音从手机扬声器拿走（和 QuickTime 一样）。打开后可在这台 Mac 上听到（需要麦克风权限）。想留在手机上请用无线镜像。Android 关闭时声音留在手机；打开后在 Mac 播放，Android 13 及以上手机也会继续出声。",
        "settings.autoOpen": "新设备出现时自动打开镜像窗口",
        "settings.wirelessMirroring": "启用无线模式",
        "settings.wirelessMirroringHelp": "通过 CoreDevice 隧道在同一局域网内连接已配对的 iPhone，并在其上运行 WebDriverAgent。首次信任、签名、安装代理以及开启 Wi‑Fi 连接仍需使用 USB。",
        "transport.usb": "USB",
        "transport.adb": "ADB",
        "transport.wireless": "无线",
        "settings.control": "控制",
        "settings.appiumURL": "Appium 服务地址",
        "settings.bundleID": "启动的 Bundle ID",
        "settings.xcodeTeam": "Apple Team ID",
        "settings.xcodeSigningID": "签名身份",
        "settings.controlAdvanced": "高级控制设置",
        "settings.wdaBundleID": "WDA Bundle ID",
        "settings.check": "检查",
        "settings.startAppium": "启动 Appium",
        "settings.stop": "停止",
        "settings.appiumHelp": "“连接控制”会先复用已有代理。首次安装时，StupidMirror 会自动检测这台 Mac 上的 Apple 开发账号；手填 Team ID 仅作为高级备用方式。",
        "settings.general": "常规",
        "toolbar.mcp": "打开 MCP 自动化设置",
        "mcp.title": "MCP 自动化",
        "mcp.server": "本机 MCP Server",
        "mcp.enabled": "自动启动 MCP Server",
        "mcp.clients": "%d 个客户端",
        "mcp.port": "端口",
        "mcp.applyPort": "应用并重启",
        "mcp.localOnly": "仅允许 127.0.0.1 访问；端口冲突时不会自动换端口。",
        "mcp.token": "Bearer Token",
        "mcp.show": "显示",
        "mcp.hide": "隐藏",
        "mcp.copyToken": "复制 Token",
        "mcp.rotateToken": "轮换 Token",
        "mcp.tokenHelp": "请把 Token 当作密码保管。轮换后，旧的 Codex 和 Claude 配置会立即失效。",
        "mcp.rotateConfirm": "确定轮换 MCP Token？现有 Codex 和 Claude 配置会立即失效。",
        "mcp.connect": "连接 Codex 或 Claude Code",
        "mcp.codexSteps": "把下面配置加入 ~/.codex/config.toml，重启 Codex，再运行 /mcp 确认 stupidmirror 已连接。删除 [mcp_servers.stupidmirror] 配置块即可移除。",
        "mcp.claudeSteps": "在终端执行下面命令，重启 Claude Code，再运行 /mcp 确认 stupidmirror。以后可运行 claude mcp remove --scope user stupidmirror 删除。",
        "mcp.copyConfig": "复制",
        "mcp.verify": "使用 MCP 时保持 StupidMirror 打开。先列出设备，点击或手势操作前先连接控制。",
        "mcp.testPrompt": "列出设备，连接控制，截图并点击设置图标。",
        "mcp.logs": "最近调用（已脱敏）",
        "mcp.noLogs": "还没有 MCP 工具调用记录。",
        "mcp.error": "MCP 错误",
        "mcp.invalidPort": "请输入 1024 到 65535 之间的端口。",
        "mcp.status.stopped": "已停止",
        "mcp.status.starting": "启动中",
        "mcp.status.running": "运行中",
        "mcp.status.failed": "失败",
        "diagnostics.runtime": "运行时",
        "diagnostics.devices": "设备",
        "diagnostics.noDevices": "当前没有可见的受支持 iOS 或 Android 设备。",
        "diagnostics.controlPrereq": "控制前置条件",
        "diagnostics.controlHelp": "Android 控制需要 USB 调试，首次连接会安装 UiAutomator2 辅助组件；iPhone 控制需要信任、开发者模式、UI Automation，以及用于 WebDriverAgent 的 Apple 签名团队。",
        "common.close": "关闭",
        "common.noUDID": "未映射 UDID",
        "common.notSet": "未设置",
        "common.default": "默认",
        "common.cancel": "取消",
        "mirror.pause": "暂停镜像",
        "mirror.start": "开始镜像",
        "mirror.disconnectControl": "断开控制",
        "mirror.home": "主屏幕",
        "mirror.appSwitcher": "App 切换器",
        "mirror.back": "返回",
        "mirror.copyScreenshot": "截图到剪贴板",
        "mirror.screenshotCopied": "截图已复制",
        "mirror.pasteClipboard": "粘贴剪贴板",
        "mirror.close": "关闭镜像",
        "mirror.floatOnTop": "保持置顶",
        "mirror.size": "窗口尺寸",
        "mirror.size.small": "小",
        "mirror.size.medium": "中",
        "mirror.size.large": "大",
        "mirror.reconnectingBody": "镜像窗口已关闭。同一台设备重新连接后会在这里恢复可用。",
        "status.ready": "就绪",
        "status.deviceConnectedRefreshing": "设备已连接，正在刷新...",
        "status.deviceDisconnectedRefreshing": "设备已断开，正在刷新...",
        "status.permissionRequired": "需要相机权限，因为 iPhone 屏幕源是通过 AVFoundation 暴露出来的。",
        "status.noSources": "没有发现受支持的设备。请连接 iPhone，或连接已开启 USB 调试的 Android 11 及以上设备，然后刷新。",
        "status.foundOne": "发现 1 台已连接设备。",
        "status.foundMany": "发现 %d 台已连接设备。",
        "status.reconnecting": "正在等待 %d 台设备重连。",
        "status.reconnectingMany": "正在等待 %d 台设备重连。",
        "status.deviceRemoved": "%@ 已移除，重新连接后会再次显示。",
        "diagnostic.camera": "相机权限",
        "diagnostic.microphone": "麦克风权限",
        "diagnostic.backend": "镜像后端",
        "diagnostic.detected": "已发现屏幕源",
        "diagnostic.reconnecting": "重连中的设备",
        "diagnostic.autoStart": "自动打开镜像",
        "diagnostic.appiumServer": "Appium 服务",
        "diagnostic.appiumService": "Appium 本机服务（不代表手机控制）",
        "diagnostic.appiumDetail": "Appium 详情",
        "diagnostic.deviceControlState": "设备 Appium 控制状态",
        "diagnostic.controlBundle": "控制 Bundle",
        "diagnostic.xcodeTeam": "Apple Team ID",
        "diagnostic.wdaBundle": "WDA Bundle",
        "diagnostic.libimobiledevice": "USB 设备信息",
        "diagnostic.mirror": "镜像",
        "diagnostic.control": "控制",
        "common.on": "开",
        "common.off": "关",
        "connection.connected": "已连接",
        "connection.disconnected": "重连中",
        "connection.unavailable": "不可用",
        "mirror.state.stopped": "已停止",
        "mirror.state.starting": "启动中",
        "mirror.state.running": "镜像中",
        "mirror.state.failed": "失败",
        "control.state.unavailable": "未连接控制",
        "control.state.activationRequired": "控制需激活",
        "control.state.connecting": "连接中",
        "control.state.connectingWDA": "正在安装或连接设备控制",
        "control.state.ready": "控制就绪",
        "control.state.failed": "控制失败",
        "control.phase.appium": "启动服务",
        "control.phase.wda": "安装代理",
        "control.phase.screen": "读取屏幕",
        "control.loading.title": "正在准备 iPhone 控制",
        "control.loading.finishing": "正在完成控制连接",
        "control.loading.expectation.short": "通常只需要几秒。",
        "control.loading.expectation.finishing": "马上就好。",
        "control.loading.elapsed": "已等待 %d:%02d",
        "control.loading.keepAwake": "请保持 iPhone 解锁和亮屏，期间不要拔掉 USB。",
        "control.loading.android.title": "正在准备 Android 控制",
        "control.loading.android.finishing": "正在完成 Android 控制连接",
        "control.loading.android.expectation.agent": "首次连接通常需要 20–60 秒，后续连接会快很多。",
        "control.loading.android.keepAwake": "请保持 Android 解锁和亮屏，不要拔掉 USB，并同意可能出现的调试提示。",
        "control.error.appiumUnavailable": "本地控制服务启动失败，请打开诊断后重试。",
        "control.error.unlockDevice": "请解锁 iPhone 并保持亮屏，然后重试安装/连接。",
        "control.error.developerMode": "请在 iPhone 上开启开发者模式，然后重试安装/连接。",
        "control.error.uiAutomation": "请为这台 iPhone 开启 UI Automation，然后重试安装/连接。",
        "control.error.trustDevice": "请在 iPhone 上信任这台 Mac，然后重新连接 USB 并重试。",
        "control.error.signing": "WDA 签名失败。请检查设置里的 Apple Team ID 和 WDA Bundle ID。",
        "appium.state.unknown": "未知",
        "diagnostic.androidADB": "Android ADB",
        "diagnostic.androidMirror": "Android 镜像运行时",
        "appium.state.checking": "检查中",
        "appium.state.starting": "启动中",
        "appium.state.running": "运行中",
        "appium.state.stopped": "已停止",
        "appium.state.missing": "未安装",
        "appium.state.failed": "失败",
        "auth.authorized": "已授权",
        "auth.notDetermined": "未决定",
        "auth.denied": "已拒绝",
        "auth.restricted": "受限",
        "auth.unknown": "未知"
    ]
}
